### PR TITLE
Implement the LUT within Fadecandy, which also fixes hotplug when in asy...

### LINKED ISSUE #563: Fadecandy LUT not implemented
I tried a few attempts and didn't get a decent curve or 1:1 working.

### PR DESCRIPTION
**Pull request by peternewman**
...nc mode. Closes #563

### CODE REVIEW

**Comment by peternewman** [comment]
Can probably also close #503 at the same time, possibly opening a new enhancement to track future stuff for the plugin.

**Comment by peternewman** [comment]
@HakanL I'd appreciate any testing you can do of this version of the code (particularly how it copes with multiple Fadecandy's), I think all the basic features are in now, still currently with the 170 pixel limit.

**Comment by peternewman** [comment]
@nomis52 can you review this ASAP, so we can get it merged in, in time for 0.9.4

**Comment by nomis52** [comment]
This all looks fine.

**Pull request merged**
