### PR TITLE
Add flake8 support

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
Just a few bits to fix :):
https://travis-ci.org/OpenLightingProject/ola/jobs/80431424

**Comment by peternewman** [comment]
Any thoughts on which bits we want to exclude?

**Comment by nomis52** [comment]
It all looks useful.

I'd turn E121 off and then try to fix the rest in this PR.

**Comment by peternewman** [comment]
Yep, I'd go with skipping E121 @nomis52 as it seems to only handle indents of four spaces.

What are your thoughts on E129, e.g. "python/ola/PidStore.py:890:7: E129 visually indented line with same indent as next logical line". I think we may have to drop that too, as otherwise it stops us nicely indenting within if etc like we'd do in C++.

**Comment by nomis52** [comment]
Agreed with skipping E129

**Comment by peternewman** [comment]
@nomis52 I've set allow failures for flake8 on Travis. Can you review what I've done so far so we can merge it in, as the remaining changes are not just whitespace and so probably need a more careful review, as they may actually break the code (not that whitespace can't do that to Python anyway).

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
