### PR TITLE
Support for Eurolite USB-DMX512-PRO MK2

### PR DESCRIPTION
**Pull request by Jazeido**
This is the successor to the original Eurolite USB-DMX512-PRO device, introduced late 2016. The protocol is identical (except that the baudrate must be set).

Code has been tested with the device.

Added the device to the USB plugin because it's nearly identical to the original Eurolite Pro. Important: There is a conflict with the Serial USB plugin which also claims the device, so Serial USB must be disabled (in the same way as FTDI USB DMX conflicts with Serial USB). This should probably be stated somewhere in the documentation ...

### CODE REVIEW

**Comment by Jazeido** [comment]
Hi @peternewman, sure, I'll fix the issues as soon as I get a chance.

**Comment by peternewman** [comment]
How are you getting on @Jazeido ?

**Comment by peternewman** [comment]
Bump @Jazeido ?

**Comment by peternewman** [comment]
CC @FreddyTinkloh

**Comment by FreddyTinkloh** [comment]
I've got the Mk2 here for the next couple weeks. I'm happy to help you guys with any testing.

**Comment by Rene2109** [comment]
Hey,

Im currently trying to get the Eurolite DMX512-Pro Mk2 Interface to work with OLA. Is there any news on this issue? How is it possible to use the Mk2 Interface with OLA?

**Comment by aroffringa** [comment]
Hi Rene. I also have the same DMX USB interface and got it to work with OLA. If you compile this branch of OLA, the Mk2 works without further changes. I've actually started to work on it a few days ago to get this branch merged in master, but some changes are required as detailed above by Peter, so for now compiling the branch is required.

**Comment by Rene2109** [comment]
Hey,
Thanks for your quick reply! I tried building the branch today by using the master branch ola and replacing the files changed in this branch (eurolite related files). Took several hours as I'm running it on a Raspberry Pi. However I'm still not able to get the Mk2 to work. Disabled all other interfering plugins (StageProfi, usbserial) but I'm still getting no (error) messages from the usbdmx plugin when I'm looking at the ola syslog. Is there anything else you did to get it to work?

**Comment by aroffringa** [comment]
I don't think I did. As long as the usb plugin is enabled, it finds it in my case. I browsed to the webserverpages, added a universe and it listed my Eurolite.

I merged the master branch into this branch by doing locally a `git pull origin master`. However, I guess the effect should be the same compared to what you did. I ran the installed program `olad` so far from the command line, with parameters equal to those normally passed by init.d (and as user olad, which is created because I also have the debian version installed). With verbose logging on it reported detecting the Eurolite on the cmdline.

**Comment by Rene2109** [comment]
When starting ola using <olad -l 4> I get some log output from the usb plugin. It seems that it detects the cendor and product ID of the interface but doesn't start the belonging eurolite code.

```
olad/PluginManager.cpp:195: Trying to start USB
libs/usb/HotplugAgent.cpp:84: libusb_set_debug(3)
libs/usb/HotplugAgent.cpp:88: HotplugSupported(): 1
libs/usb/HotplugAgent.cpp:166: USB hotplug event: 1:6 @0xd47918 [add]
plugins/usbdmx/AsyncPluginImpl.cpp:272: USB device added, checking for widget support, vendor 0x0403, product 0x6001
libs/usb/HotplugAgent.cpp:166: USB hotplug event: 1:3 @0xd49688 [add]
plugins/usbdmx/AsyncPluginImpl.cpp:272: USB device added, checking for widget support, vendor 0x0424, product 0xec00
libs/usb/HotplugAgent.cpp:166: USB hotplug event: 1:2 @0xd49fb8 [add]
plugins/usbdmx/AsyncPluginImpl.cpp:272: USB device added, checking for widget support, vendor 0x0424, product 0x9514
libs/usb/HotplugAgent.cpp:166: USB hotplug event: 1:1 @0xd33b90 [add]
plugins/usbdmx/AsyncPluginImpl.cpp:272: USB device added, checking for widget support, vendor 0x1d6b, product 0x0002
libs/usb/LibUsbThread.cpp:49: -- Starting libusb thread
common/thread/Thread.cpp:194: Thread , policy SCHED_OTHER, priority 0
libs/usb/LibUsbThread.cpp:34: ----libusb event thread is running
olad/PluginManager.cpp:200: Started USB
```

**Comment by aroffringa** [comment]
I have no idea why, but I'm also not working on a Raspberry. Maybe best to see if someone on the mailing list or irc can help you?

**Comment by peternewman** [comment]
@Rene2109 this sounds like you either haven't compiled your changes, or you're not running your compiled code. Have you got the apt version installed too? I'd remove that while you're testing to avoid confusion (sudo apt-get remove ola).

**Comment by Rene2109** [comment]
@peternewman Thanks for youre reply. I already removed the apt version before compiling the modified version. Is it possible to compile just single files, so I could test again without waiting several hours?

**Comment by peternewman** [comment]
If you run a `dpkg -l | grep -i ola` and a `which olad` and share the output of them.

It should only recompile the files that have changed, so just run make and it will do a little bit and then you can launch it.

**Comment by peternewman** [comment]
This has now gone in via https://github.com/OpenLightingProject/ola/pull/1556

**Pull request merged**
