### PR TITLE
Support for FTDI device "JMS USB2DMX PRO V2.1"

### PR DESCRIPTION
**Pull request by cmouttet**
#1728

### CODE REVIEW

**Review by peternewman — APPROVED** [review]
Brilliant thanks @cmouttet 

Feel free to add yourself to Authors if you want a credit! :smiley:

**Comment by peternewman** [comment]
Just to confirm, it does actually function and output DMX?

Also I assume it's this unit:
https://www.usb2dmx.com/en/index.php/produkte/usb2dmx-pro

You could email them to get OLA listed on their site if you were feeling keen!

**Comment by cmouttet** [comment]
> Just to confirm, it does actually function and output DMX?
> 
> Also I assume it's this unit:
> https://www.usb2dmx.com/en/index.php/produkte/usb2dmx-pro
> 
> You could email them to get OLA listed on their site if you were feeling keen!

Yes it works. Even directly plugged into my Raspberry PI, without using an active USB hub.

Side note: QLC+ uses libFTDI to drive it, Protocol "Open DMX USB", DMX frequency 30 Hz

**Comment by peternewman** [comment]
Great thanks. Sorry for the delay, our Travis continuous integration all stopped working when they migrated, it should complete and merge successfully shortly.

**Pull request merged**
