### PR TITLE
Update Debian file.

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by nomis52** [comment]
I botched the process a bit and accidentally pushed the NEWS & version increment change directly to the main repo's 0.9.7 branch.

**Comment by peternewman** [comment]
That shouldn't really matter should it, apart from a tag for the commit, we'll be able to merge the changes back in where they need to get to.

**Comment by peternewman** [comment]
LGTM

**Comment by nomis52** [comment]
Correct.

**Pull request merged**
