### PR TITLE
Reset the client socket once we've closed it, so it can be re-used

### PR DESCRIPTION
**Pull request by peternewman**
@s-light this should reduce your issues. I think this, combined with client stop, then wrapper cleanup may solve it.

### CODE REVIEW

**Comment by peternewman** [comment]
Still need to work out the best way to automate the client stop on wrapper cleanup given the separation between them.

**Comment by nomis52** [comment]
LGTM once the build issues are fixed

**Comment by s-light** [comment]
but does not solve the problem... :-|
i have applied the patch to my fork and tried it - 
output of my channel_mapper script:
```
parsing done.
switching to state_waiting
common/thread/Thread.cpp:193: Thread , policy SCHED_OTHER, priority 0
m_wrapper.Setup() 
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
....
m_wrapper.Setup() 
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
m_wrapper.Setup() 
available: 1
flag_connected: 1
switching to state_connected
switching to state_running
Connection to olad was closed
SelectServer exited.
client->Stop()
m_wrapper.Cleanup()
switching to state_waiting
m_wrapper.Setup()
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
....
m_wrapper.Setup()
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
m_wrapper.Setup()
common/io/EPoller.cpp:229: Descriptor 6 already in read set
available: 1
flag_connected: 1
switching to state_connected
switching to state_running
```
so the m_wrapper.Setup() call returned a available but there was the `Descriptor 6 aready in read set` error.

so first it seams to work - but if olad comes back online the mentioned error fails.

**Comment by peternewman** [comment]
Hmm, it would seem Travis have broken their Mac builds... :(

**Comment by s-light** [comment]
tried it  - it has changed something :-)

```
parsing done.
switching to state_waiting
common/thread/Thread.cpp:193: Thread , policy SCHED_OTHER, priority 0
m_wrapper.Cleanup(): 1
m_wrapper.Setup() 
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
...
m_wrapper.Cleanup(): 1
m_wrapper.Setup() 
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
m_wrapper.Cleanup(): 1
# ******** Here i started olad ********
m_wrapper.Setup() 
available: 1
flag_connected: 1
switching to state_connected
switching to state_running
# ******** Here i stopped olad ********
Connection to olad was closed
SelectServer exited.
client->Stop()
m_wrapper.Cleanup(): 1
switching to state_waiting
m_wrapper.Cleanup(): 1
m_wrapper.Setup() 
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
...
m_wrapper.Cleanup(): 1
m_wrapper.Setup() 
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
# ******** Here i started olad ********
m_wrapper.Cleanup(): 1
m_wrapper.Setup() 
common/io/EPoller.cpp:229: Descriptor 6 already in read set
available: 0
flag_connected: 0
...
m_wrapper.Cleanup(): 1
m_wrapper.Setup()
common/io/EPoller.cpp:229: Descriptor 6 already in read set
available: 0
flag_connected: 0
# ******** Here i stopped olad ********
m_wrapper.Cleanup(): 1
m_wrapper.Setup()
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
flag_connected: 0
...
m_wrapper.Cleanup(): 1
m_wrapper.Setup()
common/network/TCPSocket.cpp:158: connect(127.0.0.1:9010): Connection refused
available: 0
```

so now if i do a 
```
m_wrapper.Cleanup();
bool available  = m_wrapper.Setup();
```
available has the correct state :-)
it prints the `Connection refused` if olad is not running -
and if olad exited and is re started it prints the
`Descriptor 6 already in read set`

so we are getting closer :-)

**Comment by peternewman** [comment]
@nomis52 I think this bit could be merged. I'm a bit stumped/need to spend some more time pondering how to fix the next error, but won't have time for a while.

**Comment by peternewman** [comment]
Thanks @nomis52 .

**Pull request merged**
