### PR TITLE
Try and fix some more pychecker issues

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
This is just broken due to the Clang protobuf issues; #1080 will fix it.

**Comment by peternewman** [comment]
This should go green now @nomis52 when Travis finishes.

**Comment by nomis52** [comment]
You test all of these right?

**Comment by peternewman** [comment]
Yep, including tweaking the test or dummy responder to deliberately throw the errors/generate edge cases.

I did a lot of tests of the class inheritance too, to ensure it worked as expected.

Plus pychecker and flake8 check them.

**Comment by nomis52** [comment]
LGTM then

**Comment by peternewman** [comment]
And it would seem the honest answer is not quite enough yet. Some miss-programming on the TestDefinitions side with optional PIDs which were inheriting from ResponderTestFixture directly, rather than OptionalParameterTestFixture.

I'll do some more thorough testing, then get another review, but it's going to be fairly simple fixes generally.

**Comment by peternewman** [comment]
@nomis52 this has been tested, so can be merged at some point, or I'll keep doing improvements.

**Comment by peternewman** [comment]
Is the remainder of this small enough to just review as one PR now @nomis52 ?

**Comment by peternewman** [comment]
Bump @nomis52

**Pull request merged**
