### PR TITLE
Python client: Add __str__ to Port, Universe and Device

### PR DESCRIPTION
**Pull request by simark**
This is useful for logging and debugging.

If you like the format, I could change the other objects that already
have a __str__ so the format is consistent.

### CODE REVIEW

**Comment by peternewman** [comment]
Again looks fine, @nomis52 ?

**Comment by nomis52** [comment]
LGTM. I'm fine if you change the other __str__ methods.

**Comment by simark** [comment]
Updated. I made minor edits to the existing hunks (code style).

**Comment by simark** [comment]
Updated, I switched from __str__ to __repr__ for reasons outlined in the commit message.

**Pull request merged**
