### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by nils-van-zuijlen**
In plugins/e131/messages/E131ConfigMessages.proto:17
And libs/acn/E131InflatorTest.cpp:155

As requested there: https://github.com/OpenLightingProject/ola/pull/1405#pullrequestreview-117820570

### CODE REVIEW

**Comment by peternewman** [comment]
You could target our 0.10 branch if you want, but you'll probably need to cherry-pick or create some new commits. Blocked behind getting https://github.com/OpenLightingProject/ola/pull/1416 into master too.

**Comment by peternewman** [comment]
Also now blocked behind #1419 when it gets into master.

**Comment by peternewman** [comment]
Blocked behind #1420

**Comment by nils-van-zuijlen** [comment]
LGTM

**Pull request merged**
