### PR TITLE
Work around a Clang error

### PR DESCRIPTION
**Pull request by peternewman**
Backport from https://github.com/google/protobuf/commit/f01c1441bc7226bf10cf032b2b699a151020cd14

### CODE REVIEW

**Comment by nomis52** [comment]
LGTM

**Comment by peternewman** [comment]
Apart from it doesn't actually solve the issue. :(

**Comment by peternewman** [comment]
This is now ready to merge @nomis52 . I've made the compiler strictness of the tests for the protobuf stuff match that of the man code.

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
