### PR TITLE
Extend configure so we switch to C++11 if necessary for Protobuf 3.6

### PR DESCRIPTION
**Pull request by peternewman**
Closes https://github.com/OpenLightingProject/ola/issues/1463

### CODE REVIEW

**Comment by peternewman** [comment]
Oops, sorry @schelmo , I missed a case. Either give it another go or wait for Travis to do it's thing first.

**Comment by peternewman** [comment]
Third time lucky!

**Comment by schelmo** [comment]
Looks good to me.
`============================================================================
Testsuite summary for OLA 0.10.7
============================================================================
# TOTAL: 83
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0`

also is olad is working as expected

nice and thank you very much!

**Comment by alphancioglu** [comment]
I had the same issue [#1463](https://github.com/OpenLightingProject/ola/issues/1463) with schelmo and my system is also arch linux. I built this PR with gcc and got 1 error from tests.

```
============================================================================
Testsuite summary for OLA 0.10.7
============================================================================
# TOTAL: 83
# PASS:  82
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to open-lighting@googlegroups.com
============================================================================
FAIL: ola/OlaClientTester
```

**Comment by peternewman** [comment]
It's exactly that @alphancioglu . As it says in the test failure message:

> Check for another instance of olad running

If you stop the other daemon, all the tests should pass as expected.

**Pull request merged**
