### PR TITLE
Update NEWS

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by nomis52** [comment]
LGTM

**Comment by peternewman** [comment]
Mostly just a way to poke it and confirm if Travis would break.

**Comment by peternewman** [comment]
I think we need the Jan 14 onwards changes from:
https://github.com/OpenLightingProject/ola/compare/0.10...peternewman:pychecker?expand=1

**Comment by peternewman** [comment]
This is ready to merge now @nomis52 .

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
