### PR TITLE
migrate all plugin descriptions to Markdown

### PR DESCRIPTION
**Pull request by FloEdelmann**
see #1142

### CODE REVIEW

**Comment by peternewman** [comment]
Looking further, the ArtNet plugin has no dependencies, whereas Dmx4Linux does, because it doesn't have the dependencies, and hence it's not building the Description.h, is I think why it's failing.

I think you may be able to solve this by pulling this bit of code outside the if USE_DMX4LINUX bit:
# Plugin description is generated from README.md
built_sources += plugins/dmx4linux/Dmx4LinuxPluginDescription.h
plugins/dmx4linux/Dmx4LinuxPluginDescription.h: plugins/dmx4linux/README.md plugins/dmx4linux/Makefile.mk plugins/convert_README_to_header.sh
	sh $(top_srcdir)/plugins/convert_README_to_header.sh $(top_srcdir)/plugins/dmx4linux $(top_builddir)/plugins/dmx4linux/Dmx4LinuxPluginDescription.h

In which case you'll need to do it for all the others too.

**Comment by FloEdelmann** [comment]
On Mac OS, the WidgetDetectorThreadTest.cpp fails at line 367:
```
Test name: WidgetDetectorThreadTest::testUsbProWidget
equality assertion failed
- Expected: 2
- Actual  : 0
```
But I don't know why because I didn't change anything relevant to this. And it also doesn't fail on Linux.

**Comment by FloEdelmann** [comment]
Seems to work now :)

**Comment by peternewman** [comment]
Thanks for all your hard work @FloEdelmann . Do you fancy attempting the other couple of small tasks in the project?
https://github.com/OpenLightingProject/ola/projects/1

**Comment by FloEdelmann** [comment]
I can try but I'll concentrate on my exams in university in the next weeks. After that, vacation is the perfect time for OLA ;)

**Comment by peternewman** [comment]
Okay, well thanks for the work so far @FloEdelmann . I may have a look at the other bits when I get a chance.

**Pull request merged**
