### PR TITLE
[for 0.10] Remove EPoll delay

### PR DESCRIPTION
**Pull request by DaAwesomeP**
This is a cherry-picked duplicate of #1801 for v0.10.

Possible milestone #1792

cc @peternewman

### CODE REVIEW

**Review by peternewman — CHANGES_REQUESTED** [review]
Thanks @DaAwesomeP , but could we just have the changes to EPoller.cpp in here, not the test program too please.

**Comment by DaAwesomeP** [comment]
@peternewman Fixed!

**Review by peternewman — APPROVED** [review]
LGTM thanks @DaAwesomeP .

Feel free to add yourself to AUTHORS too:
https://github.com/OpenLightingProject/ola/blob/0.10/AUTHORS

**Comment by DaAwesomeP** [comment]
> Feel free to add yourself to AUTHORS too:
> https://github.com/OpenLightingProject/ola/blob/0.10/AUTHORS

Adding! One moment please.

**Comment by DaAwesomeP** [comment]
Done!

**Pull request merged**
