### PR TITLE
Fix some comments from #433

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
@Keeper-of-the-Keys I've addressed a number of the basic comments from @nomis52 review of #433 . Hopefully you can find some time to test what I've done and address some of the remaining ones?

**Comment by nomis52** [comment]
LGTM

**Comment by nomis52** [comment]
Can you pick up the 'KWMATIK' string as well please.

**Comment by Keeper-of-the-Keys** [comment]
@nomis52 What are you referencing with KWMATIK? Do you mean the 3 Vendors listed in FtdiWidget-libftdi.cpp?

I hope to start work on moving supported pid/vid pairs to the plugin conf file and then the whole vendor string & hardcoded vid/pid pairs should become obsolete....

**Comment by peternewman** [comment]
Done @nomis52 . @Keeper-of-the-Keys he meant you'd accidentally dropped support for another manufacturer (here https://github.com/OpenLightingProject/ola/pull/433/files#r25185983 ); it should have been four.

Making the hard coding obsolete will be great, but in the interim we need to ensure we don't regress any issues.

As you asked on IRC, to try my code, add me as a remote and git pull peternewman windows to get my changes.

Are you happy to pick up the remaining issues?

**Comment by nomis52** [comment]
LGTM. Merge when you're happy.

**Comment by peternewman** [comment]
Merging this now and either myself ro @Keeper-of-the-Keys can do another PR with the outstanding stuff. It will also make his testing of my changes easier, as he can just pull upstream.

**Pull request merged**
