### PR TITLE
Master Resync

### PR DESCRIPTION
**Pull request by DaAwesomeP**
For #1801

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@peternewman reminder to add weblint to the required checks.

**Comment by DaAwesomeP** [comment]
This pull also includes #1869 (pull for `0.10`) but for the `master` branch.

**Review by peternewman — APPROVED** [review]
LGTM thanks!

**Comment by peternewman** [comment]
> This pull also includes #1869 (pull for `0.10`) but for the `master` branch.

I'd generally just wait for the next merge if possible, then we can almost merge the resyncs blind as there's no new code in them.

**Comment by peternewman** [comment]
> @peternewman reminder to add weblint to the required checks.

Done thanks! 👍

**Pull request merged**
