### PR TITLE
Fix new flake8 issues due to latest pep8

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by nomis52** [comment]
Still failing..

**Comment by peternewman** [comment]
I've done all the trivial bits now. Just these left:
python/ola/OlaClient.py:759:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:783:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:807:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:829:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:853:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:879:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:905:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:931:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:959:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:996:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1022:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1061:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1107:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1133:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1220:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1254:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1274:5: E731 do not assign a lambda expression, use a def
python/ola/rpc/StreamRpcChannel.py:303:5: E731 do not assign a lambda expression, use a def
tools/rdm/ModelCollector.py:213:11: W503 line break before binary operator
tools/rdm/TestDefinitions.py:2221:13: W503 line break before binary operator

**Comment by peternewman** [comment]
@nomis52 we're now just down to these. What do you want to do about the lambdas?

We currently have:
```python
    controller = SimpleRpcController()
    request = Ola_pb2.PluginListRequest()
    done = lambda x, y: self._GetPluginsComplete(callback, x, y)
    try:
      self._stub.GetPlugins(controller, request, done)
    except socket.error:
      raise OLADNotRunningException()
    return True
```

We could either do:
```python
    controller = SimpleRpcController()
    request = Ola_pb2.PluginListRequest()
    try:
      self._stub.GetPlugins(controller, request, lambda x, y: self._GetPluginsComplete(callback, x, y))
    except socket.error:
      raise OLADNotRunningException()
    return True
```

Or def the lambda (which is probably rather redundant, as it's only used once. Is there a technical reason we can't do the inline option above?

python/ola/OlaClient.py:759:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:783:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:807:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:829:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:853:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:879:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:905:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:931:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:959:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:996:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1022:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1061:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1107:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1133:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1220:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1254:5: E731 do not assign a lambda expression, use a def
python/ola/OlaClient.py:1274:5: E731 do not assign a lambda expression, use a def
python/ola/rpc/StreamRpcChannel.py:303:5: E731 do not assign a lambda expression, use a def

**Comment by nomis52** [comment]
inline is fine

**Comment by peternewman** [comment]
I think this is finally good to go @nomis52 .

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
