### PR TITLE
Convert ola_rdm_discover to our flags module and more flake8 work

### PR DESCRIPTION
**Pull request by peternewman**
Try again to get a clean commit list.

### CODE REVIEW

**Comment by peternewman** [comment]
Replaces #946 .

**Comment by peternewman** [comment]
Sorry, I forgot this hadn't been merged, if the flake8 issues need too much work, particularly the later commit, I'll revert it for now to be revisited shortly.

**Comment by nomis52** [comment]
LGTM

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
