### PR TITLE
converted ModelCollector.py to Python3, using 2to3 tool

### PR DESCRIPTION
**Pull request by eddydebaere**
As requested in 
https://groups.google.com/forum/#!topic/open-lighting/j7x7X-4U6xk

wkr
Eddy

### CODE REVIEW

**Comment by eddydebaere** [comment]
converted ModelCollector.py to Python3, using 2to3 tool

**Comment by eddydebaere** [comment]
converted ModelCollector.py to Python3, using 2to3 tool

**Comment by peternewman** [comment]
Is there some reason this is closed @eddydebaere ?

**Comment by peternewman** [comment]
There are a few suggestions in here for how to make the code Python 2 and 3 compatible, without the speed hits of dropping to range in Python 2:
http://stackoverflow.com/questions/15014310/why-is-there-no-xrange-function-in-python3

**Comment by eddydebaere** [comment]
The speed penalties are only relevant for large  (or frequently accessed) ranges/lists. In this case, 
the range is only 13 elements, and only 1 access. Therefore, I would keep it easy, and just use 'range'.

**Comment by eddydebaere** [comment]
The speed penalties are only relevant for large  (or frequently accessed) ranges/lists. In this case, 
the range is only 13 elements, and only 1 access. Therefore, I would keep it easy, and just use 'range'.

**Pull request closed without merging**
