### PR TITLE
Fix protoc version checking, since v20.x

### LINKED ISSUE #1867: New protoc versioning breaks configure
```
checking for protoc... /usr/local/bin/protoc
+ test -z /usr/local/bin/protoc
+ test -n 2.3.0
+ printf '%s\n' 'configure:25925: checking protoc version'
+ printf %s 'checking protoc version... '
++ /usr/local/bin/protoc --version
++ grep libprotoc
++ sed 's/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/g'
+ protoc_version='libprotoc 23.3'
+ required=2.3.0
++ echo 2.3.0
++ sed 's/[^0-9].*//'
+ required_major=2
++ echo 2.3.0
++ sed 's/[0-9][0-9]*\.\([0-9][0-9]*\)\.[0-9][0-9]*/\1/'
+ required_minor=3
++ echo 2.3.0
++ sed 's/^.*[^0-9]//'
+ required_patch=0
++ echo libprotoc 23.3
++ sed 's/[^0-9].*//'
+ actual_major=
++ echo libprotoc 23.3
++ sed 's/[0-9][0-9]*\.\([0-9][0-9]*\)\.[0-9][0-9]*/\1/'
+ actual_minor='libprotoc 23.3'
++ echo libprotoc 23.3
++ sed 's/^.*[^0-9]//'
+ actual_patch=3
++ expr '>' 2 '|' = 2 '&' libprotoc 23.3 '>' 3 '|' = 2 '&' libprotoc 23.3 = 3 '&' 3 '>=' 0
expr: syntax error
+ protoc_version_proper=
+ test '' = 1
+ as_fn_error 1 'protoc version too old libprotoc 23.3 < 2.3.0' 25948 5
+ as_status=1
+ test 1 -eq 0
+ test 5
+ as_lineno=25948
+ as_lineno_stack=as_lineno_stack=
+ printf '%s\n' 'configure:25948: error: protoc version too old libprotoc 23.3 < 2.3.0'
+ printf '%s\n' 'configure: error: protoc version too old libprotoc 23.3 < 2.3.0'
configure: error: protoc version too old libprotoc 23.3 < 2.3.0
```

See https://github.com/OpenLightingProject/ola/actions/runs/5341378456/jobs/9682134019

https://protobuf.dev/support/version-support/

### PR DESCRIPTION
**Pull request by peternewman**
Closes #1867

### CODE REVIEW

**Comment by topas-rec** [comment]
I'm trying to build this and I'm getting issue #1867.
Does anyone know a way around that issue here? I don't want to cross compile, just x86_64.
I use [this arch pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ola-git)  and change it's source to this branch.

**Comment by peternewman** [comment]
> I'm trying to build this and I'm getting issue ~#1867~ #1864 .

Can you share your config.log please?

Alternatively have a look here for something else to test that might help...:
https://github.com/OpenLightingProject/ola/issues/1867#issuecomment-1631629938

**Comment by topas-rec** [comment]
> Can you share your config.log please?

Sure

<details>

<summary>ola-git configuration log</summary>

```
==> Making package: ola-git 0.10.6.r1355.g671e66b85-1 (Wed 12 Jul 2023 07:26:36 CEST)
==> Retrieving sources...
  -> Cloning ola git repo...
Cloning into bare repository '/home/tobiasb/.cache/yay/ola-git/ola'...
remote: Enumerating objects: 87035, done.
remote: Counting objects: 100% (1199/1199), done.
remote: Compressing objects: 100% (470/470), done.
remote: Total 87035 (delta 766), reused 1094 (delta 727), pack-reused 85836
Receiving objects: 100% (87035/87035), 24.32 MiB | 6.77 MiB/s, done.
Resolving deltas: 100% (65913/65913), done.
==> Validating source files with sha256sums...
    ola ... Skipped
:: (1/1) Parsing SRCINFO: ola-git
==> Making package: ola-git 0.10.6.r1355.g671e66b85-1 (Wed 12 Jul 2023 07:26:42 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating ola git repo...
==> Validating source files with sha256sums...
    ola ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of ola git repo...
Cloning into 'ola'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Updated version: ola-git 0.9.4.r3324.g35c035ed9-1
==> Sources are ready.
==> Making package: ola-git 0.9.4.r3324.g35c035ed9-1 (Wed 12 Jul 2023 07:26:45 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config'.
libtoolize: copying file 'config/libtool.m4'
libtoolize: copying file 'config/ltoptions.m4'
libtoolize: copying file 'config/ltsugar.m4'
libtoolize: copying file 'config/ltversion.m4'
libtoolize: copying file 'config/lt~obsolete.m4'
configure.ac:140: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:140: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:140: the top level
configure.ac:381: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
configure.ac:381: the top level
configure.ac:30: installing 'config/compile'
configure.ac:226: installing 'config/config.guess'
configure.ac:226: installing 'config/config.sub'
configure.ac:13: installing 'config/install-sh'
configure.ac:13: installing 'config/missing'
Makefile.am:199: warning: .PHONY was already defined in condition DX_COND_doc, which is included in condition TRUE ...
aminclude.am:161: ... '.PHONY' previously defined here
Makefile.am:15:   'aminclude.am' included from here
Makefile.am:236: warning: .PHONY was already defined in condition DX_COND_doc, which is included in condition TRUE ...
aminclude.am:161: ... '.PHONY' previously defined here
Makefile.am:15:   'aminclude.am' included from here
Makefile.am:240: warning: .PHONY was already defined in condition DX_COND_doc, which is included in condition TRUE ...
aminclude.am:161: ... '.PHONY' previously defined here
Makefile.am:15:   'aminclude.am' included from here
Makefile.am:245: warning: error flake8 not found. Install flake8 and re-run configure.: non-POSIX variable name
Makefile.am:245: (probably a GNU make extension)
Makefile.am:250: warning: shell find . \( -name "*.h" -or -name "*.cpp" \: non-POSIX variable name
Makefile.am:250: (probably a GNU make extension)
Makefile.am:259: warning: .PHONY was already defined in condition DX_COND_doc, which is included in condition TRUE ...
aminclude.am:161: ... '.PHONY' previously defined here
Makefile.am:15:   'aminclude.am' included from here
Makefile.am:264: warning: error cpplint not found. Install the forked cpplint (e.g. via pip for the latest version: non-POSIX variable name
Makefile.am:264: (probably a GNU make extension)
Makefile.am:283: warning: .PHONY was already defined in condition DX_COND_doc, which is included in condition TRUE ...
aminclude.am:161: ... '.PHONY' previously defined here
Makefile.am:15:   'aminclude.am' included from here
Makefile.am:286: warning: error Generating coverage requires configuring with --enable-gcov: non-POSIX variable name
Makefile.am:286: (probably a GNU make extension)
Makefile.am:292: warning: error gcovr not found. Install gcovr (e.g. via pip for the latest version: non-POSIX variable name
Makefile.am:292: (probably a GNU make extension)
Makefile.am: installing './INSTALL'
Makefile.am: installing 'config/depcomp'
python/ola/Makefile.mk:17: installing 'config/py-compile'
Makefile.am:177:   'python/Makefile.mk' included from here
python/Makefile.mk:2:   'python/ola/Makefile.mk' included from here
parallel-tests: installing 'config/test-driver'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gawk... (cached) gawk
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for -std=gnu++98 support... yes
checking for -std=gnu++11 support... yes
configure: checking for random gnu++98 compatibility
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for vfork.h... no
checking for sys/select.h... yes
checking for sys/socket.h... yes
checking for random... no
configure: checking for random gnu++11 compatibility
checking for random... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for errno.h... yes
checking for arpa/inet.h... yes
checking for bits/sockaddr.h... yes
checking for fcntl.h... yes
checking for float.h... yes
checking for limits.h... yes
checking for malloc.h... yes
checking for netinet/in.h... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for sys/file.h... yes
checking for sys/ioctl.h... yes
checking for sys/socket.h... (cached) yes
checking for sys/time.h... yes
checking for sys/timeb.h... yes
checking for syslog.h... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking for asm/termbits.h... yes
checking for asm/termios.h... yes
checking for assert.h... yes
checking for dlfcn.h... yes
checking for endian.h... yes
checking for execinfo.h... yes
checking for linux/if_packet.h... yes
checking for math.h... yes
checking for net/ethernet.h... yes
checking for stropts.h... no
checking for sys/ioctl.h... (cached) yes
checking for sys/param.h... yes
checking for sys/types.h... (cached) yes
checking for sys/uio.h... yes
checking for sysexits.h... yes
checking for winsock2.h... no
checking for winerror.h... no
checking for random... yes
checking for sys/sysctl.h... no
checking for net/if.h... yes
checking for net/if_arp.h... yes
checking for net/route.h... yes
checking for net/if_ether.h... no
checking for netinet/if_ether.h... yes
checking for linux/netlink.h... yes
checking for linux/rtnetlink.h... yes
checking for _Bool... no
checking for stdbool.h that conforms to C99... yes
checking how to run the C++ preprocessor... g++ -E
checking for uid_t in sys/types.h... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for pid_t... yes
checking for C/C++ restrict keyword... no
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking the location of hash_map... <unordered_map>
checking for fork... yes
checking for vfork... yes
checking for vprintf... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for GNU libc compatible malloc... yes
checking for GNU libc compatible realloc... yes
checking for working memcmp... yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking whether lstat correctly handles trailing slash... yes
checking whether stat accepts an empty string... no
checking whether closedir returns void... no
checking for bzero... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for strdup... yes
checking for strrchr... yes
checking for if_nametoindex... yes
checking for inet_ntoa... yes
checking for inet_ntop... yes
checking for inet_aton... yes
checking for inet_pton... yes
checking for select... yes
checking for socket... yes
checking for strerror... yes
checking for getifaddrs... yes
checking for getloadavg... yes
checking for getpwnam_r... yes
checking for getpwuid_r... yes
checking for getgrnam_r... yes
checking for getgrgid_r... yes
checking for secure_getenv... yes
checking for clock_gettime... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... (cached) yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for linux/version.h... yes
checking for Linux epoll(7) interface... yes
checking for kqueue... no
checking for -rdynamic support... yes
checking for IPv6 support... no
checking for struct sockaddr.sa_len... no
checking for struct sockaddr_dl.sdl_family... no
checking for time_t... yes
checking for suseconds_t... yes
checking for g++ options needed to detect all undeclared functions... none needed
checking whether MSG_NOSIGNAL is declared... yes
checking whether SO_NOSIGPIPE is declared... no
checking whether PF_ROUTE is declared... yes
checking whether NET_RT_DUMP is declared... no
checking whether RLIMIT_RTPRIO is declared... yes
checking whether RLIMIT_RTTIME is declared... yes
checking whether SO_REUSEADDR is declared... yes
checking whether SO_REUSEPORT is declared... yes
checking for termios2... yes
checking for linux/spi/spidev.h... yes
checking for bison... bison
checking for flex... flex
checking for lex output file root... lex.yy
checking for lex library... none needed
checking for library containing yywrap... no
checking whether yytext is a pointer... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for library containing dlopen... none required
checking for DMXdev in -ldmx4linux... no
checking for dmx/dmxioctl.h... no
checking for library containing clock_gettime... none required
checking for backtrace in -lexecinfo... no
checking for curses.h... yes
checking for ncurses/curses.h... no
checking for initscr in -lncurses... yes
checking for libncurses... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for pthread_np.h... no
checking for 2-arg pthread_setname_np... yes
checking for resolv.h... (cached) yes
checking for res_init() in -lresolv... yes
checking whether res_ninit is declared... yes
checking for base_uuid... yes
checking for uuid/uuid.h... yes
checking for uuid_generate in -luuid... yes
checking for dns_sd.h... yes
checking for library containing DNSServiceRegister... -ldns_sd
checking for avahi... yes
checking for SaleaeDeviceApi.h... no
configure: WARNING: SaleaeDevice library is not usable.
checking for libmicrohttpd... yes
checking for MHD_create_response_from_buffer... yes
checking for libftdi0... yes
checking for libftdi1... yes
checking for libusb... yes
checking for libusb_error_name... yes
checking for libusb_hotplug_api... yes
checking for libusb_set_option... yes
checking for asm/termios.h... (cached) yes
checking for liblo... yes
checking for serial port lock directory... /var/lock
checking whether python version is >= 2.6... yes
checking for python version... 3.11
checking for python platform... linux
checking for GNU default python prefix... ${prefix}
checking for GNU default python exec_prefix... ${exec_prefix}
checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.11/site-packages
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.11/site-packages
checking for python module: google.protobuf... yes
checking for flake8... no
checking for libprotobuf... yes
checking for protoc... /usr/bin/protoc
checking protoc version... 23.4.0
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: Cannot find the protoc header files
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: ola-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
ola-git - exit status 4
```

</details>

> Alternatively have a look here for something else to test that might help...:
https://github.com/OpenLightingProject/ola/issues/1867#issuecomment-1631629938

I'll try that when I'm back at that machine. Thanks.

**Comment by peternewman** [comment]
> > Can you share your config.log please?
> 
> Sure
> ola-git configuration log

That's not quite what I'm looking for unfortunately. When it runs ./configure within that process, that should generate a file called config.log with a more verbose view of the configuration stage (and the failure).

> I'll try that when I'm back at that machine. Thanks.

Thanks.

**Comment by topas-rec** [comment]
[config.log](https://github.com/OpenLightingProject/ola/files/12031126/config.log)
_I cannot put this in here as text and even pastebin doesn't accept that size._

Most likely this is the problem: `error: static assertion failed: Protobuf only supports C++14 and newer.`

**Comment by topas-rec** [comment]
>Alternatively have a look here for something else to test that might help...:
https://github.com/OpenLightingProject/ola/issues/1867#issuecomment-1631629938

I picked the two commits with the version check into [my C14 branch](https://github.com/topas-rec/ola/tree/0.10-c14-compat) and added `--with-protoc=/usr/bin/protoc` (from https://github.com/OpenLightingProject/ola/issues/1864#issue-1762515033) to the build command and I get this far in configuration:

```
[...]
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.11/site-packages
checking for python module: google.protobuf... yes
checking for flake8... no
checking for libprotobuf... yes
set protoc to /usr/bin/protoc
checking protoc version... 23.4.0
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: Cannot find the protoc header files
```

**Comment by peternewman** [comment]
> I picked the two commits with the version check into [my C14 branch](https://github.com/topas-rec/ola/tree/0.10-c14-compat)

That looks fine.

> and added `--with-protoc=/usr/bin/protoc` (from [#1864 (comment)](https://github.com/OpenLightingProject/ola/issues/1864#issue-1762515033)) to the build command

You don't need that bit unless you're trying to cross-compile, which I suspect you aren't.

> and I get this far in configuration:
> 
> ```
> [...]
> checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.11/site-packages
> checking for python module: google.protobuf... yes
> checking for flake8... no
> checking for libprotobuf... yes
> set protoc to /usr/bin/protoc
> checking protoc version... 23.4.0
> checking for google/protobuf/compiler/command_line_interface.h... no
> configure: error: Cannot find the protoc header files
> ```

Again this doesn't tell us enough and we need the config.log which will have a more informative error like you found above, but also some key info in the lines above the error, like did my gnu++11 flagging get correctly through to that code...

**Comment by topas-rec** [comment]
This is the config.log from my c14 branch mentioned above:
[config.log](https://github.com/OpenLightingProject/ola/files/12035610/config.log)

**Comment by peternewman** [comment]
Okay, because we're getting lots of discussion about the same stuff in lots of different places, please continue any further discussion around issues with newer protoc that aren't our versioning tests in #1879 .

**Comment by kripton** [comment]
Sorry that it took me so long.
This PR changes the error message from (0.10 branch):
```
checking for python3.10 module: google.protobuf... yes
checking for flake8... no
checking for libprotobuf... yes
checking protobuf library version... 23.3.0
checking for protoc... /usr/bin/protoc
checking protoc version... expr: syntax error: unexpected argument '2'
configure: error: protoc version too old libprotoc 23.3 < 2.3.0
``` 

to
```
checking for python3.10 module: google.protobuf... yes
checking for flake8... no
checking for libprotobuf... yes
checking for protoc... /usr/bin/protoc
checking protoc version... 23.3.0
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: Cannot find the protoc header file
```

on my machine featureing protobuf 23.3-r2 and protobuf-c 1.4.1-r1

I need yet to find out why but since it IS able to detect the version of protoc correctly, I would merge this now. I might further investigate this tomorrow evening

**Review by kripton — APPROVED** [review]
Formal approval since the changes look good and they work for people. Header problem is probably local to my machine

**Comment by peternewman** [comment]
> Sorry that it took me so long. This PR changes the error message from (0.10 branch):
> 
> on my machine featureing protobuf 23.3-r2 and protobuf-c 1.4.1-r1
> 
> I need yet to find out why but since it IS able to detect the version of protoc correctly, I would merge this now. I might further investigate this tomorrow evening. The file is sitting right here: `/usr/include/google/protobuf/compiler/command_line_interface.h`

What does your config.log look like?

**Comment by jasger9000** [comment]
Why is this pr not merged, the header problem does not look to be related to the version parsing.

**Comment by peternewman** [comment]
I think I was hoping for some more positive noises from someone else @jasger9000 . As far as I can see, my tests on action runs have been the only successful usage of this change, and aside from running `make check` they won't have had any testing afterwards.

Does the change work for you and does OLA function correctly afterwards?

**Comment by jasger9000** [comment]
> I think I was hoping for some more positive noises from someone else @jasger9000 . As far as I can see, my tests on action runs have been the only successful usage of this change, and aside from running `make check` they won't have had any testing afterwards.

Not completely, unfortunately, I also hang at the script not finding my protoc header files, the regex however works perfectly.
It is even more bizarre that it cannot find the headers, since they are present in the directory and have the right permissions set.

This looks however like a misconfiguration of `AC_CHECK_HEADER(
      [google/protobuf/compiler/command_line_interface.h],
      [],
      AC_MSG_ERROR([Cannot find the protoc header files]))` in the ola.m4 file.

> Does the change work for you and does OLA function correctly afterwards?

I currently don't have a manual build, since I use a build from the [proaudio](https://github.com/osam-cologne/archlinux-proaudio) Arch Linux repo since they had an up-to-date binary available.

**Comment by cbix** [comment]
@jasger9000 there is no easy fix for that in ola because the underlying issue is missing C++14 compatibility, see #1879.

I'll add the protoc compat package from @topas-rec to the proaudio repo later and finally fix the ola PKGBUILD for that. Will have to check for potential conflicts with the official protoc package tho.

**Comment by peternewman** [comment]
> Not completely, unfortunately, I also hang at the script not finding my protoc header files, the regex however works perfectly. It is even more bizarre that it cannot find the headers, since they are present in the directory and have the right permissions set.

Okay that will do me, I've merged it now.

As @cbix notes, the reason it fails is because of C++14 (or even later compatibility) as tracked in the other issue.

If you look at the config.log it has stuff like this:
```
configure:25981: checking for google/protobuf/compiler/command_line_interface.h
configure:25981: g++ -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -std=gnu++14   conftest.cpp >&5
In file included from /usr/include/absl/types/optional.h:39,
                 from /usr/include/absl/container/internal/common.h:22,
                 from /usr/include/absl/container/internal/btree.h:63,
                 from /usr/include/absl/container/btree_map.h:56,
                 from /usr/include/google/protobuf/compiler/command_line_interface.h:48,
                 from conftest.cpp:178:
/usr/include/absl/utility/utility.h:164:12: error: 'in_place_t' has not been declared in 'std'
  164 | using std::in_place_t;
      |            ^~~~~~~~~~
```

in_place_t is I think C++17 (not even 14!).

**Comment by kripton** [comment]
So, where do we go from here? Merge #1841, release 0.11.x, then bring the codebase to C++17 and do an 0.12.x? Just as a rough plan? I tend to say that the 0.10.x branch is getting EOL slowly ....

**Pull request merged**
