### PR TITLE
Use the build matrix subset for packages

### PR DESCRIPTION
**Pull request by peternewman**
https://github.com/travis-ci/travis-ci/issues/3505

### CODE REVIEW

**Comment by nomis52** [comment]
Travis seems unhappy.

**Comment by peternewman** [comment]
Yes it still needs some work @nomis52, but I think I'm getting there now.

**Comment by nomis52** [comment]
LGTM

Does this help with caching at all?

**Comment by peternewman** [comment]
It won't really affect caching, but reduces what needs installing, so we'll get better results when llvm is being flaky, as well as contributing to the flakiness less by reducing how much we hammer them.

**Pull request merged**
