### PR TITLE
FTDI DMX allow the same universe to be patched to multiple ports

### PR DESCRIPTION
**Pull request by peternewman**
Or patch port 2 before port 1

Fixes @Keeper-of-the-Keys 's comments in #1219, but not the core of that bug!

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
OK checked it and it makes 4 unnamed (no port X) instances of the board available.

**Comment by peternewman** [comment]
Great thanks @Keeper-of-the-Keys . So it's not made it worse? But we probably need to work on the port naming so you know which of the specific ports to patch for a physical output?

And you can patch them in the order you want (e.g. selecting the second one first), or indeed more than one to the same universe?

**Comment by Keeper-of-the-Keys** [comment]
@peternewman You just have a list of 4 instances, they seem to be in-order but of course if you choose to assign the second port first only the person who did the assigning will now that the second item listed currently is the 3rd port.

I think it is acceptable to have it like this but I/we should implement proper names of the ports asap, I'll be happy to cook up a patch if you give me some pointers.

**Comment by Keeper-of-the-Keys** [comment]
Actually even if you assigned the 1st port first the second item should always be the 3rd port so that was a bad example, but in this case the first listed item would be the 1st and not the second port, you get the picture.

**Comment by peternewman** [comment]
Okay great, merged as is then.

**Comment by peternewman** [comment]
Further patch discussion to continue in #1219 .

**Pull request merged**
