### PR TITLE
Fix configure to mangle AM_LDFLAGS instead of LDFLAGS, which it has no business to mangle.

### LINKED ISSUE #1201: Configure doesn't check for tcmalloc's presence when trying to add it to libs
Instead it errors on the first compilation after that test:
```
configure:22278: g++ -o conftest -g -O2 -std=gnu++98 -pthread   -ltcmalloc conftest.cpp  -ldl  -lprotoc >&5
/usr/bin/ld: cannot find -ltcmalloc
collect2: error: ld returned 1 exit status
configure:22278: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OLA"
| #define PACKAGE_TARNAME "ola"
| #define PACKAGE_VERSION "0.10.3"
| #define PACKAGE_STRING "OLA 0.10.3"
| #define PACKAGE_BUGREPORT "open-lighting@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "ola"
| #define VERSION "0.10.3"
| #define HAVE_DIRENT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_ARPA_NAMESER_H 1
| #define HAVE_NETDB_H 1
| #define HAVE_RESOLV_H 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_ARPA_INET_H 1
| #define HAVE_BITS_SOCKADDR_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_FLOAT_H 1
| #define HAVE_LIMITS_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_FILE_H 1
| #define HAVE_SYS_IOCTL_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_SYS_TIMEB_H 1
| #define HAVE_SYSLOG_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_ASM_TERMIOS_H 1
| #define HAVE_ASSERT_H 1
| #define HAVE_DLFCN_H 1
| #define HAVE_ENDIAN_H 1
| #define HAVE_EXECINFO_H 1
| #define HAVE_LINUX_IF_PACKET_H 1
| #define HAVE_MATH_H 1
| #define HAVE_NET_ETHERNET_H 1
| #define HAVE_STROPTS_H 1
| #define HAVE_SYS_PARAM_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_UIO_H 1
| #define HAVE_SYSEXITS_H 1
| #define HAVE_SYS_SYSCTL_H 1
| #define HAVE_NET_IF_H 1
| #define HAVE_NET_IF_ARP_H 1
| #define HAVE_NET_ROUTE_H 1
| #define HAVE_NETINET_IF_ETHER_H 1
| #define HAVE_LINUX_NETLINK_H 1
| #define HAVE_LINUX_RTNETLINK_H 1
| #define HAVE_STDBOOL_H 1
| #define restrict __restrict
| #define HAVE_HASH_MAP 1
| #define HAVE_HASH_SET 1
| #define HAVE_UNORDERED_MAP 1
| #define HASH_MAP_H <tr1/unordered_map>
| #define HASH_SET_H <tr1/unordered_set>
| #define HASH_NAMESPACE std::tr1
| #define HASH_MAP_CLASS unordered_map
| #define HASH_SET_CLASS unordered_set
| #define HAVE_FORK 1
| #define HAVE_VFORK 1
| #define HAVE_WORKING_VFORK 1
| #define HAVE_WORKING_FORK 1
| #define HAVE_STDLIB_H 1
| #define HAVE_MALLOC 1
| #define HAVE_STDLIB_H 1
| #define HAVE_REALLOC 1
| #define HAVE_SYS_SELECT_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define SELECT_TYPE_ARG1 int
| #define SELECT_TYPE_ARG234 (fd_set *)
| #define SELECT_TYPE_ARG5 (struct timeval *)
| #define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
| #define HAVE_VPRINTF 1
| #define HAVE_BZERO 1
| #define HAVE_GETTIMEOFDAY 1
| #define HAVE_MEMMOVE 1
| #define HAVE_MEMSET 1
| #define HAVE_MKDIR 1
| #define HAVE_STRDUP 1
| #define HAVE_STRRCHR 1
| #define HAVE_IF_NAMETOINDEX 1
| #define HAVE_INET_NTOA 1
| #define HAVE_INET_NTOP 1
| #define HAVE_INET_ATON 1
| #define HAVE_INET_PTON 1
| #define HAVE_SELECT 1
| #define HAVE_SOCKET 1
| #define HAVE_STRERROR 1
| #define HAVE_GETIFADDRS 1
| #define HAVE_GETLOADAVG 1
| #define HAVE_GETPWNAM_R 1
| #define HAVE_GETPWUID_R 1
| #define HAVE_GETGRNAM_R 1
| #define HAVE_GETGRGID_R 1
| #define HAVE_SECURE_GETENV 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_EPOLL 1
| #define HAVE_TIME_T 1
| #define HAVE_SUSECONDS_T 1
| #define HAVE_DECL_MSG_NOSIGNAL 1
| #define HAVE_DECL_SO_NOSIGPIPE 0
| #define HAVE_DECL_PF_ROUTE 1
| #define HAVE_DECL_NET_RT_DUMP 0
| #define HAVE_DECL_RLIMIT_RTPRIO 1
| #define HAVE_DECL_RLIMIT_RTTIME 1
| #define HAVE_DECL_SO_REUSEADDR 1
| #define HAVE_DECL_SO_REUSEPORT 1
| #define HAVE_TERMIOS2 1
| #define HAVE_PTHREAD_SETNAME_NP_2 1
| #define HAVE_RESOLV_H 1
| #define HAVE_DECL_RES_NINIT 1
| #define HAVE_UUID_UUID_H 1
| #define HAVE_LIBUUID 1
| #define HAVE_AVAHI 1
| #define HAVE_LIBMICROHTTPD 1
| #define HAVE_MHD_CREATE_RESPONSE_FROM_BUFFER 1
| #define HAVE_LIBFTDI 1
| #define HAVE_LIBUSB 1
| #define HAVE_LIBUSB_ERROR_NAME 1
| #define HAVE_LIBUSB_HOTPLUG_API 1
| #define HAVE_ASM_TERMIOS_H 1
| #define HAVE_UART 1
| #define HAVE_LIBLO 1
| #define UUCP_LOCK_DIR "/var/lock"
| /* end confdefs.h.  */
| #include <google/protobuf/compiler/command_line_interface.h>
| int
| main ()
| {
| google::protobuf::compiler::CommandLineInterface cli
|   ;
|   return 0;
| }
configure:22281: error: cannot find libprotoc
```

### PR DESCRIPTION
**Pull request by yoe**
Fix #1201 

While at it, fix configure to mangle AM_LDFLAGS instead of LDFLAGS, which it has no business to mangle.

### CODE REVIEW

**Comment by peternewman** [comment]
Thanks @yoe !

Can we target the tcmalloc bit at the 0.10 branch please as it's a bugfix, but perhaps the LDFLAGS stuff should stay in master, in case it's got unintended consequences.

**Comment by peternewman** [comment]
See #1243 for the fix for #1201 .

**Comment by peternewman** [comment]
@yoe do the other LDFLAGS references in the m4 scripts in config want fixing too then? https://github.com/OpenLightingProject/ola/search?utf8=%E2%9C%93&q=LDFLAGS&type=

**Comment by yoe** [comment]
No, they don't. Those all use the pattern

    save_LDFLAGS=$LDFLAGS
(mangle LDFLAGS, run various tests)

    MY_LDFLAGS=foo
    LDFLAGS=$save_LDFLAGS

etc, which means that while they touch `LDFLAGS`, they don't actually permanently change things. This is perfectly okay and the right thing to do.

**Comment by peternewman** [comment]
This will go green after #1248 goes in.

**Pull request merged**
