### PR TITLE
Open the correct interface on the EurolitePro Widget in async mode.

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by nomis52** [comment]
I checked the other calls and Eurolight is the only one where we dynamically try to find the correct interface #.

**Comment by peternewman** [comment]
LGTM. I thought Coverity might have flagged that as an unused variable, although I guess its like not using a return code.

**Comment by peternewman** [comment]
Do we need to update NEWS, or was this change all in 0.9.6?

**Comment by nomis52** [comment]
Added

**Pull request merged**
