### PR TITLE
Fix/udev rules

### PR DESCRIPTION
**Pull request by bitte-ein-bit**
udev rules are invalid format

### CODE REVIEW

**Comment by bitte-ein-bit** [comment]
@peternewman here you go.

**Comment by peternewman** [comment]
How did you get the error exactly @bitte-ein-bit ? I'm wondering if we can add validating the udev rules to our Travis tasks.

**Comment by bitte-ein-bit** [comment]
Well, I wondered why the rules would not apply. Rebooting did not load the rules. I googled a reload command, then it would show up in syslog. But before I had already spotted the missing commas, but was unsure on the syntax.

This error would be catched by https://github.com/pavlinux/udev/blob/master/test/rule-syntax-check.py. In this folder is also a simple test suite.

**Comment by peternewman** [comment]
Could I also trouble you to update https://github.com/OpenLightingProject/raspberrypi/blob/master/etc/udev/rules.d/10-local.rules with the comma too? Or feel free to tell me to get lost and I'll do it myself...

**Pull request merged**
