### PR TITLE
Some minor tidying after #433

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
I realised after I merged it, I'm not sure you actually reviewed https://github.com/OpenLightingProject/ola/pull/433 so if you see any issues in that, let me know and I'll fix them in here too.

**Comment by nomis52** [comment]
LGTM.

**Comment by nomis52** [comment]
I left comments on #433

**Comment by peternewman** [comment]
@Keeper-of-the-Keys feel free to comment too if you want, or better yet test. I don't think I changed anything significant. Thanks for your work getting the initial PR in.

**Comment by peternewman** [comment]
I've started fixing those issues in https://github.com/OpenLightingProject/ola/pull/646.

**Pull request merged**
