### PR TITLE
Fix comparison methods for python3

### PR DESCRIPTION
**Pull request by nils-van-zuijlen**
See https://portingguide.readthedocs.io/en/latest/comparisons.html#rich-comparisons for an explaination of why it was broken.

In particular, I was stuck with a bug in the `_Event` class because heaps are ordered and I wanted to add multiple events to it, which failed because they had no suitable comparison functions.

### CODE REVIEW

**Comment by peternewman** [comment]
Thanks @nils-van-zuijlen . Initially it might be worth a quick read of https://github.com/OpenLightingProject/ola/pull/1514 and some of the discussion linked to from #1506 .

Do you fancy targetting our 0.10 branch?

I'd started trying to get Python 3 builds working in Travis, if you fancy continuing that as it still needs some work (working on the principal we should probably have some tests to catch these failures in future)...
https://github.com/OpenLightingProject/ola/compare/master...peternewman:0.10-python3?expand=1

**Comment by peternewman** [comment]
All Mac builds are failing for some reason outside your control. :disappointed:

**Comment by nils-van-zuijlen** [comment]
Yes, I saw it. Apparently GitHub syncronisation failed :cry:

**Comment by peternewman** [comment]
> Yes, I saw it. Apparently GitHub syncronisation failed

Looks like it's progressing third time around...

**Comment by nils-van-zuijlen** [comment]
Now it works !

**Comment by nils-van-zuijlen** [comment]
I rebased my commits for 0.10 in #1538

**Pull request closed without merging**
