### PR TITLE
Fix UART DMX plugin on Bullseye and more recent Linux distributions

### LINKED ISSUE #1749: Uarts on RPi4 stopped working (Bullseye & ola 0.10.8)
Hi

After a fresh install of RpiOs Bullseye and sudo apt install ola (v0.10.8)
the uarts on the pi4 stopped working.
When i stop the olad daemon and intead 
run olad -l 2 -c /etc/ola i get this output:

plugins/uartdmx/UartWidget.cpp:180: Failed to set baud rate to 250k
plugins/uartdmx/UartDmxPlugin.cpp:82: Unable to setup device for output, device ignored /dev/ttyAMA0
plugins/uartdmx/UartWidget.cpp:180: Failed to set baud rate to 250k
plugins/uartdmx/UartDmxPlugin.cpp:82: Unable to setup device for output, device ignored /dev/ttyAMA1
plugins/uartdmx/UartWidget.cpp:180: Failed to set baud rate to 250k
plugins/uartdmx/UartDmxPlugin.cpp:82: Unable to setup device for output, device ignored /dev/ttyAMA2
plugins/uartdmx/UartWidget.cpp:180: Failed to set baud rate to 250k
plugins/uartdmx/UartDmxPlugin.cpp:82: Unable to setup device for output, device ignored /dev/ttyAMA3
plugins/uartdmx/UartWidget.cpp:180: Failed to set baud rate to 250k
plugins/uartdmx/UartDmxPlugin.cpp:82: Unable to setup device for output, device ignored /dev/ttyAMA4

On my old installation (Buster & ola v0.10.7) everything is working
now the question is what make it break?
Is it the upgrade to Bulleye or the upgrade of ola from 0.10.7 to 0.10.8?

I'm a bit confused about the init_uart_clock=16000000
does this set the clock for ttyAMA0 or for all uarts?
or is it the plugin that sets the baudrate? 
(it seems like it from the errors above).

So the upgrade worked as a downgrade 
The Pi4 now have instead of having 4 more uarts than a pi3 have one less (0).

Any ideas why this happened?

Thanks
/Magnus

### PR DESCRIPTION
**Pull request by peternewman**
Essentially just include a different combination of headers, but add some required cotton wool around this.

Closes #1749

With huge thanks to @plugz for mcallegari/qlcplus@5116d98

### CODE REVIEW

**Comment by peternewman** [comment]
Also @shenghaoyang was there in https://github.com/OpenLightingProject/ola/pull/1750#issuecomment-968248725 but it wasn't immediately obvious because our existing `asm/termios.h` include stuff wasn't in there example.

**Comment by gnosis953** [comment]
Sorry, might be a simple mistake. But i get error: "aminclude.am:35 ***Missing seperator. stop"

when executing make operation.

Also i had to rename the following files:
Makefile.am => Makefile.in
./java/Makefile.am => Makefile.in

because ./configure said it could not finde the two files.

Thank
you in Advance

**Comment by peternewman** [comment]
> Sorry, might be a simple mistake. But i get error: "aminclude.am:35 ***Missing seperator. stop"
> Also i had to rename the following files: Makefile.am => Makefile.in ./java/Makefile.am => Makefile.in

Yes it is simple thankfully, you need to run `autoreconf -i` first to make those files if you've sourced the code from Git.

Next time you'd be better off opening an issues about something like this.

**Comment by gnosis953** [comment]
I used autoreconf bevor. 

Seemed to be another mistake. I pulled the merge and it worked.

**Pull request merged**
