### PR TITLE
Switch to g++-5 for Travis

### PR DESCRIPTION
**Pull request by peternewman**
Don't merge in until we've had a successful Coverity build with g++-4.9

### CODE REVIEW

**Comment by peternewman** [comment]
Closes #764

**Comment by nomis52** [comment]
LGTM

**Comment by peternewman** [comment]
Confusingly this hasn't caught the error in #765 despite not having the fix merged into this branch yet:
https://github.com/peternewman/ola/blob/windows/plugins/e131/e131/PDU.cpp

May need to try a newer gcc-5

**Comment by peternewman** [comment]
Ignore me, there's the error, the pull builds the merge, my branch builds without the merge and fails:
https://travis-ci.org/peternewman/ola/jobs/65705463

**Comment by nomis52** [comment]
Looks fine. Merge when the timer expires..

**Comment by peternewman** [comment]
Coverity ran fine, so merging.

**Pull request merged**
