### PR TITLE
Update Travis to GCC6, provide a workaround for #1028

### PR DESCRIPTION
**Pull request by peternewman**
Provides a workaround for #1028 .

### CODE REVIEW

**Comment by nomis52** [comment]
LGTM

**Comment by peternewman** [comment]
Thanks, we may as well wait for #1081 to get merged before merging this.

**Comment by peternewman** [comment]
@nomis52 this lot is good to go know. Do you think we should cherry-pick the #1028 fix into 0.10.3?

**Comment by peternewman** [comment]
@sl1200mk2 confirmed this fixed the build for him on Arch with GCC 6.1.1, so cherry-picking this sounds like it would be worthwhile.

**Comment by nomis52** [comment]
Can you do a separate PR with the resync please. It's hard to keep track of the changes.

**Comment by peternewman** [comment]
This just has the changes now @nomis52 .

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
