### PR TITLE
Add a helper method to convert an RDMResponse to a NACKing RDMResponse

### PR DESCRIPTION
**Pull request by peternewman**
(cherry picked from commit 324b4ec341d20d121c57e61afc6d272a6951d0c1)

### CODE REVIEW

**Comment by peternewman** [comment]
Ping @kripton in case you missed it...

**Review by kripton — APPROVED** [review]
Looks all good, new test case PASSes on my machine and FAILs if I modify it (just to make sure it was actually run)

**Comment by kripton** [comment]
@peternewman: Interesting, even though the branch is in your repo, I was able to rebase it on top of latest master using GitHub's web interface. I'll merge it as soon as all CI checks are green.

**Comment by peternewman** [comment]
> @peternewman: Interesting, even though the branch is in your repo, I was able to rebase it on top of latest master using GitHub's web interface.

That may be because of this:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Or possibly simply because you've got OLA write access, but I suspect not unless that box was ticked from the description...

**Pull request merged**
