### PR TITLE
Switch to using pthread_equal rather than operator==

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by peternewman** [comment]
If you're doing this, can you remove the == operator too please.

**Comment by peternewman** [comment]
As mentioned on IRC, I suspect based on https://github.com/OpenLightingProject/ola/commit/c30041c1095246ae578c66bc53f5a8f464052e32 it may be needed elsewhere, but I guess we just need to suck it and see on Windows again and see what breaks.

**Comment by peternewman** [comment]
Actually can't we just redefine the == operator to work on ThreadId and not touch/specialise the test?

**Comment by nomis52** [comment]
Since ThreadId is typedefs to the native thread type, I don't want to define a operator== since it may conflict with the system definition.

I'm going to leave the operator== in place and let @nightrune remove it. I don't want to break the Windows build any more than I have to.

**Comment by peternewman** [comment]
Okay @nomis52

**Pull request merged**
