### PR TITLE
Fix build errors with musl C library.

### PR DESCRIPTION
**Pull request by bkuhls**

### CODE REVIEW

**Comment by bkuhls** [comment]
Here is the logfile of the broken compile
http://autobuild.buildroot.net/results/17f/17fe88868acdbba074561da14c4417e31d506823/build-end.log

**Comment by peternewman** [comment]
Have you tried with 0.10.0?

Can you target our 0.10 branch please?

**Comment by bkuhls** [comment]
Yes, the bug is also present in 0.10.0. Shall I send a new PR for the 0.10 branch?

**Comment by nomis52** [comment]
Yes please.

**Comment by bkuhls** [comment]
Done: https://github.com/OpenLightingProject/ola/pull/1025

**Pull request closed without merging**
