### PR TITLE
Fix the build on Ubuntu

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
I don't know if we want class versus no class standardised or is there some reason for that which I've missed?

**Comment by nomis52** [comment]
You need the class if you haven't included the .h file:

https://en.wikipedia.org/wiki/Forward_declaration#Classes

**Comment by peternewman** [comment]
Do we want to standardise one way or the other then?

**Comment by nomis52** [comment]
It depends on the use case.

If the class only appears as a pointer or a template arg like this, there is an advantage to not including the *.h since it'll speed up the build.

**Pull request merged**
