### PR TITLE
Create philips_hue_osram_lightify.conf (replaces the file philips_hue_lux.conf)

### PR DESCRIPTION
**Pull request by gobo-ws**
This config file also works with Osram Lightify products when they are connected to a Philips Hue bridge.
Should possible also work with GE Link, Cree Connected and Dresden FLS-PP lp (not tested though)

This config file has been updated with support for Osram Lightify plug:
http://www.osram.com/osram_com/products/electronics/lightify-controls/lightify-home/lightify-plug/index.jsp

### CODE REVIEW

**Comment by peternewman** [comment]
Thanks @gobo-ws . Can you make the final change of deleting the old file here, and then it should automagically appear in this PR:
https://github.com/gobo-ws/ola/tree/master

**Comment by peternewman** [comment]
Also you'll need to change this line @gobo-ws to fix the check:
https://github.com/gobo-ws/ola/blob/master/tools/ola_trigger/Makefile.mk#L76

**Comment by gobo-ws** [comment]
Hi Peter, I hope everything is ok now?
philips_hue_lux.conf has been removed and https://github.com/gobo-ws/ola/blob/master/tools/ola_trigger/Makefile.mk#L76 has been fixed.
Best Regards, Johan

**Comment by peternewman** [comment]
LGTM @gobo-ws .

@nomis52 any final comments?

**Comment by peternewman** [comment]
Retrospective if you want @nomis52 .

**Pull request merged**
